source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'kk_buluo' do
	  pod 'SDWebImage', '4.4.6'
   	pod 'AFNetworking'
    pod 'YYText'
    pod 'YYImage'
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'bench_ios', :svn => 'https://jingtian@huored.gicp.net:8088/svn/bench_ios/trunk/bench_ios_net/bench_ios’
    pod 'AMapLocation'
    pod 'AMapSearch'
    pod 'Masonry'
    pod 'FMDB'
    pod 'RongCloudIM/IMKit', '2.9.14'
    pod 'Bugly', '2.5.0'
    pod 'lottie-ios', '2.5.3'
    pod 'ZBarSDK', '~> 1.3.1'
end
