//
//  ThirdWebViewController.m
//  JCZJ
//
//  Created by mac on 2017/2/13.
//  Copyright © 2017年 apple. All rights reserved.
//

#import "ThirdWebViewController.h"
//#import "GNavView.h"
//#import "GWHProgressHUD.h"
//#import "DPToast.h"



@interface ThirdWebViewController ()<UIWebViewDelegate>
{
//    GNavView *_nav;
    UIWebView *_webView;
    UILabel *_backgroundLabel;
//    GWHProgressHUD *_HUD;
}
@end

@implementation ThirdWebViewController

- (void)viewDidLoad {
    [super viewDidLoad];
//    self.view.backgroundColor = COLOR_BOTTOM;
//    _nav=[[GNavView alloc]initWithFrame:CGRectMake(0, 0, SCREEN_WIDTH, STATUS_AND_NAV_BAR_HEIGHT)];
//    [self.view addSubview:_nav];
    
    UIButton *backButton=[UIButton buttonWithType:UIButtonTypeCustom];
    backButton.frame=CGRectMake(0, STATUS_BAR_HEIGHT, 44, 44);
    backButton.imageEdgeInsets = UIEdgeInsetsMake ( 11 , 11 , 11 , 11);
    [backButton setImage:[UIImage imageNamed:@"顶部-返回"] forState:UIControlStateNormal];
    [self.view addSubview:backButton];
    [backButton addTarget:self action:@selector(backButtonTapped) forControlEvents:UIControlEventTouchUpInside];
    
    
    _webView = [[UIWebView alloc] initWithFrame:CGRectMake(0, STATUS_AND_NAV_BAR_HEIGHT, SCREEN_WIDTH, SCREEN_HEIGHT-STATUS_AND_NAV_BAR_HEIGHT)];
    _webView.delegate = self;
    NSURLRequest *request = [NSURLRequest requestWithURL:[NSURL URLWithString:_url]];
    [_webView loadRequest:request];
    [self.view addSubview:_webView];
    
    _backgroundLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, -44, SCREEN_WIDTH, 20)];
    _backgroundLabel.textColor = [UIColor colorWithRed:0.322 green:0.322 blue:0.322 alpha:1.00];
    _backgroundLabel.font = [UIFont systemFontOfSize:12];
    _backgroundLabel.numberOfLines = 0;
    _backgroundLabel.textAlignment = NSTextAlignmentCenter;
    _backgroundLabel.backgroundColor = [UIColor clearColor];
    UIView *contentView = _webView.scrollView.subviews.firstObject;
    [contentView addSubview:_backgroundLabel];
    
//    _HUD = [[GWHProgressHUD alloc] init];
//    [self.view addSubview:_HUD];
}
-(void)webViewDidStartLoad:(UIWebView *)webView
{
    _backgroundLabel.text = @"loading";
//    _nav.titleLabel.text = @"loading";

}
-(void)webViewDidFinishLoad:(UIWebView *)webView
{
//    [_HUD removeFromSuperview];
    
    _backgroundLabel.text = [NSString stringWithFormat:@"This page was generated by \"%@\"",webView.request.URL.host];

    NSString *title = [_webView stringByEvaluatingJavaScriptFromString:@"document.title"];
    if (title.length > 10) {
        title = [[title substringToIndex:9] stringByAppendingString:@"…"];
    }
//    _nav.titleLabel.text = title;
}

-(void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error
{
    _backgroundLabel.text = [NSString stringWithFormat:@"%@%@",@"load failed:" , error.localizedDescription];
//    _nav.titleLabel.text = @"load failed";
//    
//    [_HUD removeFromSuperview];
//    [[DPToast makeText:[NSString stringWithFormat:@"%@",@"出错啦，无法打开网页"]] showWithOffset:SCREEN_HEIGHT/3.0*2];
}


-(void)backButtonTapped
{
    [self.navigationController popViewControllerAnimated:YES];
}

@end
